### ISSUE TITLE
( Joinville - SC) Designer /UX Pl/ Sr e Lead na (The Bridge)

### ISSUE THREAD

**Issue by Gabithebridge** [remotejobsbr/design-ux-vagas#1]
Interessados direcionarem o cv para gabriela.sobral@thebridge.social
Description
Empresa Nacional que usa a tecnologia para criar uma plataforma em nuvem, onde o empreendedor juntamente com o seu contador, de forma simples e fácil, podem encontrar tudo o que precisam em tempo real. 

RESPONSABILIDADES

Transformar problemas em experiências surpreendentes para nossos clientes;
Tomar decisões baseadas em dados (quantitativos e qualitativos) e utilizar métodos, teorias e ferramentas de design como apoio;
Capacidade de aplicar métodos de validação como testes de usabilidade presenciais e remotos;
Manter o time informado sobre os aprendizados obtidos em campo com os usuários.

HABILIDADES E CONHECIMENTOS DESEJÁVEIS

Ser pró-ativo (a) e ter muita vontade de aprender;
Ser comunicativo (a) e trabalhar bem em grupo;
Atenção aos detalhes;
Capacidade de aprender novas ferramentas;
Capacidade de evoluir elementos baseando-se em descobertas;
Ter formação relacionada a área;
Conhecimento em design de sistemas e experiência do usuário;
Conhecimento e aplicar técnicas de facilitação de dinâmicas;
Habilidade de prototipar com bibliotecas de componentes;
Inglês avançado.

BENEFÍCIOS

Vale refeição/alimentação; 
Auxílio educação e pós graduação;
Auxílio idioma;
Convênio com farmácias;
Plano de saúde integral e sem desconto em folha;
Plano odontológico integral e sem desconto em folha;
Auxílio atividade física;
Vale transporte;
Auxílio mudança (se você for de fora);
Resume highlighting

**Comment by alexgmello** [comment]
Não sei se ainda estão procurando, mas por via das dúvidas enviei meu currículo.
Atualmente estou no RJ, mas não tenho problemas em me realocar.
